### ISSUE TITLE
deployment history in portal?

### ISSUE THREAD

**Issue by billwert** [Azure/actions-workflow-samples#45]
This probably isn't precisely the right place for this question, for which I apologize in advance.

I've configured the action successfully and it reports deployment success. However, because I didn't configure it through the Deployment Center in the portal for my function app, I can't see deployment history in the Azure portal to know it really, _really_ worked. :)

Is there a way to see deployment history that I'm missing?

**Comment by ehamai** [comment]
Hi there.  If you've already configured a workflow file external to Deployment Center, it's still possible to configure DC so that it knows about it.  Just go into DC and go through the setup process as usual.  DC will check to see if there is an existing workflow file in your repo.  If there is, just choose the "use existing workflow file" option and it won't try to add a new one for you.  Hope that helps.
